version: '3'
services:
  postgres:
    image: postgres:15
    container_name: strapi-postgres
    environment:
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: Strapi@123
      POSTGRES_DB: strapi_real_estate
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: